[package]
name = "reco-view-cli"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
reco-view.workspace = true
tracing-subscriber.workspace = true
